"""add structured content fields to proposal model

Revision ID: 7b6d4d67e324
Revises: 9a6e37957675
Create Date: 2025-11-15 20:49:14.530640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6d4d67e324'
down_revision: Union[str, Sequence[str], None] = '9a6e37957675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('structured_content', sa.JSON(), nullable=True, comment='结构化内容 {abstract, background, objectives, etc.}'))
    op.add_column('proposals', sa.Column('word_count', sa.Integer(), nullable=True, comment='总字数统计'))
    op.add_column('proposals', sa.Column('version', sa.Integer(), nullable=False, comment='版本号（乐观锁）'))
    op.add_column('proposals', sa.Column('last_auto_save_at', sa.DateTime(timezone=True), nullable=True, comment='最后自动保存时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'last_auto_save_at')
    op.drop_column('proposals', 'version')
    op.drop_column('proposals', 'word_count')
    op.drop_column('proposals', 'structured_content')
    # ### end Alembic commands ###
