"""Initial database schema with User and Proposal models

Revision ID: 9a6e37957675
Revises: 
Create Date: 2025-11-15 11:56:02.526333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6e37957675'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('full_name', sa.String(length=100), nullable=False, comment='真实姓名'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='哈希密码（bcrypt）'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('institution', sa.String(length=200), nullable=True, comment='所属机构'),
    sa.Column('department', sa.String(length=200), nullable=True, comment='所属院系'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='职位'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('research_field', sa.String(length=100), nullable=True, comment='研究方向'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='账户是否激活'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='是否为管理员'),
    sa.Column('email_verified', sa.Boolean(), nullable=True, comment='邮箱是否已验证'),
    sa.Column('is_edu_email', sa.Boolean(), nullable=True, comment='是否为教育邮箱'),
    sa.Column('verify_token', sa.String(length=255), nullable=True, comment='邮箱验证令牌'),
    sa.Column('verify_token_expires', sa.DateTime(timezone=True), nullable=True, comment='令牌过期时间'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True, comment='登录失败次数'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='账户锁定至'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='注册时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='draft/reviewing/completed/submitted'),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('funding_agency', sa.String(length=200), nullable=True, comment='资助机构'),
    sa.Column('funding_amount', sa.Integer(), nullable=True, comment='申请金额（万元）'),
    sa.Column('project_duration', sa.Integer(), nullable=True, comment='项目期限（月）'),
    sa.Column('research_field', sa.String(length=100), nullable=True, comment='研究领域'),
    sa.Column('keywords', sa.JSON(), nullable=True, comment='关键词数组'),
    sa.Column('quality_score', sa.Float(), nullable=True, comment='综合质量 0-10'),
    sa.Column('content_score', sa.Float(), nullable=True, comment='内容质量 0-10'),
    sa.Column('format_score', sa.Float(), nullable=True, comment='格式规范 0-10'),
    sa.Column('innovation_score', sa.Float(), nullable=True, comment='创新程度 0-10'),
    sa.Column('ai_suggestions', sa.JSON(), nullable=True, comment='AI 修改建议'),
    sa.Column('ai_analysis', sa.JSON(), nullable=True, comment='AI 分析报告'),
    sa.Column('files', sa.JSON(), nullable=True, comment="附件列表 [{'name': '...', 'url': '...'}]"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True, comment='提交时间'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_id'), 'proposals', ['id'], unique=False)
    op.create_index(op.f('ix_proposals_title'), 'proposals', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposals_title'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
